### ISSUE TITLE
A parameter cannot be found that matches parameter name 'TimeOut'.

### ISSUE THREAD

**Issue by kevschu2** [FSLogix/Invoke-FslShrinkDisk#36] opened 2021-03-11 08:42 UTC
have used your script successfully before.  Though, when i tried to run it tonight I am getting "

A parameter cannot   be found that matches parameter name 'TimeOut'.
--

" on all profiles that should be getting shrunk.

When the script is run using Powershell 7+ i get " 

Failed to mount   disk - "The process cannot access the file because it is being used by   another process. "
--

"

**Comment by JimMoyle** [comment] 2021-03-11 09:41
So there isn't a parameter 'TimeOut' what command did you use to run the script?

Also 'The failed to mount disk' error is usually caused by the user who owns the disk being logged in.  Is this the case?

Thanks

Jim

**Comment by kevschu2** [comment] 2021-03-11 17:17
This was the command that I ran, both in PS5.x and 7.x and received the differing results.

.\Invoke-FslShrinkDisk.ps1 -path \\share\profiles -recurse -ignoreLessThanGB 25 -DeleteOlderThanDays 120

The errors above happened on the same profiles.  so perhaps the timeout error has something to do with the locked profile?

**Comment by JimMoyle** [comment] 2021-03-11 17:39
Did you get the error message on screen or in the logs?

**Comment by kevschu2** [comment] 2021-03-12 00:55
errors showed up in the logs/csv

**Comment by rbj46-42** [comment] 2021-03-29 16:32
I am having the same issue.
I am running the command:
PS C:\RDS_FXlogix\Invoke-FslShrinkDisk-master> .\Invoke-FslShrinkDisk.ps1 -Path "G:\profile.vhdx" -ThrottleLimit 1 -RatioFreeSpace 0 -PassThru


Name           : profile.VHDX
StartTime      : 18:24:29
EndTime        : 18:24:29
ElapsedTime(s) : 0
DiskState      : A parameter cannot be found that matches parameter name 'TimeOut'.
OriginalSizeGB : 8,22
FinalSizeGB    : 8,22
SpaceSavedGB   : 0
FullName       : G:\profile.vhdx

**Comment by JimMoyle** [comment] 2021-03-29 18:06
Can you give me a download link to the problematic vhd?

**Comment by rbj46-42** [comment] 2021-03-30 05:51
> Can you give me a download link to the problematic vhd?

Hej Jim

I have sent you an mail through github👍

Thanks so far

**Comment by rbj46-42** [comment] 2021-03-30 15:39
We had a look at the issue and could not reproduce the issue.

The script works great :)

**Comment by JimMoyle** [comment] 2021-03-30 15:48
Closing due to no repro, thanks rbj

**Closed by JimMoyle** 2021-03-30 15:48 UTC
