### ISSUE TITLE
Error on first disk to enter RunSpace

### ISSUE THREAD

**Issue by JAK1047** [FSLogix/Invoke-FslShrinkDisk#12] opened 2020-08-13 15:18 UTC
I'm finding the first disk when recursing always errors out dumping "Failed to read partition information for disk - "The input name "Type" cannot be resolved to a property."" to the log. For example I have 2 disks in a folder the second one it attempts will work. If I make a copy so there are 3 now the copy errors out and the other 2 work. Flipping on verbose it looks like it never even mounts the errored out disk.

Judging from the error I'm assuming either line 774 or 1309 are the failing cmds:

$partition = Get-Partition -DiskNumber $mountedDisk.Number | Where-Object -Property 'Type' -eq -Value 'Basic'

If I set the throttlelimit to 1 they all work, so guessing it's something with the first object going into the runspace pool?

**Comment by JimMoyle** [comment] 2020-08-14 14:47
Not sure how this would occur if they all work with the throttle limit as 1 as then all disks are the first into the pool.  If you have some time I could take a look.  You can contact me with the email associated with my github account.

**Comment by JAK1047** [comment] 2020-08-14 19:55
Sure thing I shot you an email.

**Comment by TheMuffnMan** [comment] 2020-08-19 14:29
I can confirm setting the throttle limit to 1 appears to correct the issue.

**Comment by Ben-ITLogic** [comment] 2020-08-21 00:05
Confirmed that I am seeing the same thing after testing last night.

**Comment by JimMoyle** [comment] 2020-08-25 14:27
So I've made some changes, adding retries etc. can you test the script i this branch?

https://github.com/FSLogix/Invoke-FslShrinkDisk/tree/Optimize-OneDisk

Thanks

Jim

**Comment by TheMuffnMan** [comment] 2020-08-30 16:01
Will give it a test here this week! Thanks Jim

**Comment by ZevZev** [comment] 2020-09-02 07:59
Hi Jim,

I downloaded the new version, and ran into a huge issue:

It did compact a lot of disks, but, it kept them all open in some way. I didn't notice that myself - but next morning we got a P1 incident where end-users reported not being able to log in because their profile disks couldn't be mounted/opened. Which of course made sense as they were still open on the server.

I couldn't find a quick way how to close all the open disks/files on the server itself, se we ended up rebooting the server.

This is a new issue. With the previous version of the script we had some disks that couldn't be compacted, and some that were corrupt after running the script. But corruption that could be fixed with chkdsk or repair-volume.

But those issues were minor compared to this version. Any idea why all disks were kept open after running the script?
We use CloudCache, and it happened on both fileservers that we use for this.

Cheers,

Jaap

**Comment by JimMoyle** [comment] 2020-09-02 09:17
So are you running the script from a VM with very few cores?  The dismount is now timing out as well.  Also please don't test stuff in production.  I'll add some retries to the dismount too.

It shouldn't be possible to corrupt disks with the script as I don't touch the data inside, but I'd like to know more about exactly what errors you needed to fix with chkdsk.

**Comment by ConnorKirby** [comment] 2020-09-14 20:36
I have tested with the new branch but still seeing this issue. I have tried this with the below command:

.\Invoke-FslShrinkDisk.ps1 -Path \\<server-name>\FSLogixProfiles\<user-name> -Recurse -PassThru -LogFilePath c:\365profile.csv

When doing this, I am still seeing the same error but it appears the disk keeps attached. The script does move onto the ODFC and runs fine. 

If a specify the full path profile disk path and name, rather than the user's folder, it seems to run - on my test case, it came back with SkippedAlreadyMinimum - the profile is only 1.59GB so likely this is correct and the disk is then detached. Is this expected behaviour, or should I be able to run the script at the top-level folder?

**Comment by JimMoyle** [comment] 2020-09-18 13:41
So I've made some more updates with a lot or error catching, can you try out this patch?

https://github.com/FSLogix/Invoke-FslShrinkDisk/tree/Optimize-OneDisk

Jim

**Comment by ConnorKirby** [comment] 2020-09-22 20:32
I've run the new update - this time, I the tool runs on the profile and reports 'SkippedAlreadyMinimum' but no longer leaves the profile disk attached.

We have also been using ShrinkFSL (http://www.citrixirc.com/?p=1052) straight after running the latest release, I ran ShrinkFSL and this was able to reduce by 130MB. 

Although we now get a different error message, it doesn't seem to still be able to touch the profiles, only ODFC's. Our profiles are VHDs whereas ODFCs are VHDXs.

**Closed** 2021-08-18 09:02 UTC
